### ISSUE TITLE
Individual players promoting their games on their social media pages

### ISSUE THREAD

**Issue by tjmacphee** [TeachingData/SportProject#18]
Need to have teams make their own posts on their social media accounts, or pick someone to manage their teams social media account to provide updates & promote their own games/merch/stats

**Comment by jsgreenwell** [comment]
Unfortunetly (or fortunetly because I'm glad we cannot do this) we cannot force people to use or advertise anything on their personal accounts. However, a volunteer option might be possible but still out of our control.
